### ISSUE TITLE
Missing property from class extended @MappedSuperclass with maven module as dependency

### ISSUE THREAD

**Issue by rbygrave** [ebean-orm/avaje-ebeanorm-mavenenhancer#6]
https://github.com/ebean-orm/avaje-ebeanorm/issues/200

This issue was logged on avaje-ebeanorm as #200 above.

**Comment by rbygrave** [comment]
I have confirmed this issue exists in 4.5.1 of the maven enhancer and is fixed in 4.6.1

**Comment by rbygrave** [comment]
Note the stacktrace in particular is:

Caused by: java.lang.IllegalStateException: Property id not found in [email, password, confirm, active, roles]
    at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.setBeanReflect(BeanDescriptorManager.java:1309)
    at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.createByteCode(BeanDescriptorManager.java:1134)
    at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readDeployAssociations(BeanDescriptorManager.java:1050)
    at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityDeploymentAssociations(BeanDescriptorManager.java:529)
    at com.avaje.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:241)
    at com.avaje.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:116)
    at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:185)
    at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:106)
    at com.avaje.ebeaninternal.server.core.DefaultServerFactory.createServer(DefaultServerFactory.java:46)
    at com.avaje.ebean.EbeanServerFactory.create(EbeanServerFactory.java:37)
    at com.avaje.ebean.Ebean$ServerManager.getWithCreate(Ebean.java:206)
    at com.avaje.ebean.Ebean$ServerManager.<init>(Ebean.java:162)
    at com.avaje.ebean.Ebean$ServerManager.<init>(Ebean.java:128)
    at com.avaje.ebean.Ebean.<clinit>(Ebean.java:122)
    ... 25 more
